spring:
  data:
    mongodb:
      username: ilyass
      password: ilyass123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
